<footer>

  <div class="container-fluid">

    <div class="row-fluid fit-to-design site-links">

      <div class="span3">
        <h1><?=App::xlat('about_site')?></h1>
        <ul class="unstyled">
          <li> <i class="icon-cog"></i> <a href="<?=App::url_translate('requirements_link')?>"><?=App::xlat('requirements')?></a></li>
          <li> <i class="icon-file-alt"></i> <a href="<?=App::url_translate('terms_conditions_link')?>"><?=App::xlat('terms_conditions')?></a></li>
        </ul>
        <h1><?=App::xlat('social_networks')?></h1>
        <ul class="unstyled">
          <li> <i class="icon-facebook"></i> <a href="<?=App::getConfig('url_facebook')?>">Facebook</a></li>
          <li> <i class="icon-twitter"></i> <a href="<?=App::getConfig('url_twitter')?>">Twitter</a></li>
          <li> <i class="icon-google-plus"></i> <a href="<?=App::getConfig('url_google')?>">Google Plus!</a></li>
          <li> <i class="icon-facetime-video"></i> <a href="<?=App::getConfig('url_youtube')?>">Youtube</a></li>
        </ul>
      </div>

      <div class="span3">
        <h1><?=App::xlat('recomend')?></h1>
        <ul class="unstyled">
          <li> <i class="icon-external-link"></i> <a href="http://www.asambleaapostolicamexico.com" target="blank">Asamblea Apostólica México</a>  </li>
          <li> <i class="icon-external-link"></i> <a href="http://www.lavoz.org" target="blank">La voz de la esperanza</a>  </li>
          <li> <i class="icon-external-link"></i> <a href="http://www.antesdelfin.com" target="blank">Antes del fin</a>  </li>
          <li> <i class="icon-external-link"></i> <a href="http://seguidoresdelreydereyes.blogspot.com/" target="blank">Seguidores del Rey de reyes</a>  </li>
        </ul>
      </div>

      <div class="span3 scroll-this">
        <h1><?=App::xlat('hours')?></h1>
        <em> <?=App::xlat('dates_long_day_1')?> </em>
        <ul class="unstyled">
          <li><?=App::xlat('leader_meeting')?></li>
          <li><?=App::xlat('pray')?></li>
        </ul>
        <em> <?=App::xlat('dates_long_day_6')?> </em>
        <ul class="unstyled">
          <li><?=App::xlat('child_class')?></li>
          <li><?=App::xlat('prince_class')?></li>
        </ul>
        <em> <?=App::xlat('dates_long_day_7')?> </em>
        <ul class="unstyled">
          <li><?=App::xlat('first_sermon')?></li>
          <li><?=App::xlat('second_sermon')?></li>
          <li><?=App::xlat('third_sermon')?></li>
        </ul>
      </div>

      <div class="span3">
        <h1><?=App::xlat('address')?></h1>
        <p class="address"><?=App::xlat('address_full')?></p>
        <p><?=App::xlat('address_hours')?></p>
        <p>
          <i class="icon-phone"></i> <?=App::xlat('address_phone_1')?> <br />
          <i class="icon-phone"></i> <?=App::xlat('address_phone_2')?>
        </p>
      </div>
    </div>

    <div class="row-fluid fit-to-design copyrights">
      <div class="span6 rights"> &copy; <a href="<?=App::url_translate()?>"><?=App::getConfig('website_name')?></a> <?=date('Y')?>. <?=App::xlat('ALL_RIGHTS_RESERVED')?></div>
      <div class="span6 logo">
        <img src="<?=App::media('/images/flexar.png')?>" alt="<?=App::xlat('FLEXAR_slogan')?>" title="<?=App::xlat('FLEXAR_slogan')?>" />
      </div>
    </div>

  </div>
</footer>