  <div class="left-panel">
    <h1>
      <?=$this->aboutus['title']?>
      <span><?=App::xlat('CONTENT_subtitle_aboutus')?></span>
    </h1>
    <p>
      <?= eval('?>' . $this->aboutus['article'] . '<?php ');?>
    </p>
  </div>

  <div class="right-panel">
    <?=App::module('Addons')->renderBlock("youtube/index","show-video", array(  'id'       => '_YTYaB7fP-A'
                                                                              , 'title'    => App::xlat('YOUTUBE_video_about_title')
                                                                              , 'subtitle' => App::xlat('YOUTUBE_video_about_subtitle') ) );?>
  </div>