  <div class="left-panel">
    <h1><?=App::xlat('CELL_title')?>
      <span><?=App::xlat('CELL_subtitle')?></span>
    </h1>
    <img height="150" width="645" title="<?=App::xlat('CELL_subtitle')?>" alt="<?=App::xlat('CELL_subtitle')?>" src="<?=App::media('/images/cell.jpg') ?>" />
    <p><?=App::xlat('CELL_pharagraph_1')?></p>
    <br />
    <p><?=App::xlat('CELL_pharagraph_2')?></p>
    <br />
    <p><?=App::xlat('CELL_pharagraph_3')?></p>

    <?php if( ! empty($this->cells) ):?>
      <br />
      <h1 class="no-line"><?=App::xlat('CELL_map_adress_title')?>
        <span><?=App::xlat('CELL_map_adress_subtitle')?></span>
      </h1>

      <?php 
        foreach($this->cells AS $cell){
          $tabs['tab'][ $cell['zone_id'] ]   = "<li><a href='#'>{$cell['zone']}</a></li>";
          $tabs['panes'][ $cell['zone_id'] ][] =
            "<p class='address'>
               <a class='map' href='http://maps.google.com/maps?f=q&source=s_q&hl=en&geocode=&q=Fredrikstad,+Norway&sll=37.0625,-95.677068&sspn=40.324283,93.076172&ie=UTF8&z=11&ll=59.263073,10.963669&output=embed' onclick='return hs.htmlExpand(this, { objectType: \"iframe\" } )'>
                 <img class='map' src='". App::media('/location/' . $cell['map_image'] ) ."' />
               </a>
               <strong>{$cell['name']}</strong>
               <em>{$cell['adress']}</em>
               <em>{$cell['phone']}</em>
               <em>{$cell['hours']}</em>
             </p>";
        }
      ?>

      <ul class="tabs">
        <?=implode('',$tabs['tab']);?>
      </ul>

      <div class="panes">
        <?php foreach($tabs['tab'] AS $key=>$tab):?>
          <div><?=implode('',$tabs['panes'][$key]);?></div>
        <?php endforeach;?>
      </div>

    <?php endif;?>

  </div>

  <div class="right-panel">
    <?=App::module('Addons')->renderBlock("site/index","social-networks");?>
    <?=App::module('Articles')->renderBlock("index","promote", array('past_next'=>'next') );?>
  </div>

<?php 
/*
$cells
Array
(
    [id] => 1
    [status] => enabled
    [created] => 2012-05-04 09:10:58
    [updated] => 2012-05-04 09:10:58
    [modified] => arthasmx@gmail.com
    [map_cordinates] => 
    [map_image] => default_map.png
    [name] => Hector Mejia
    [adress] => Avenida cascara seca #234 Los Mangos 3
    [phone] => 6691-522-565
    [hours] => Martes 7:30pm
    [zone] => Zona 1
    [sector] => Sector 2
    [lang] => es
    [zone_id] => 1
    [sector_id] => 2
)
 */
?>