  <div class="left-panel">
    <h1><?=App::xlat('CELL_title')?>
      <span><?=App::xlat('CELL_subtitle')?></span>
    </h1>
    <img height="150" width="645" title="<?=App::xlat('CELL_subtitle')?>" alt="<?=App::xlat('CELL_subtitle')?>" src="<?=App::media('/images/cell.jpg') ?>" />
    <p><?=App::xlat('CELL_pharagraph_1')?></p>
    <br />
    <p><?=App::xlat('CELL_pharagraph_2')?></p>
    <br />
    <p><?=App::xlat('CELL_pharagraph_3')?></p>
  </div>

  <div class="right-panel">
    <h1>A ver que ponemos aqui<span>Sed congue, dui vel tristique mollis...</span></h1>
    <p><strong>Address Info</strong><br />123 Pine Street<br />Mycity, ST 19000</p>
    <p><strong>Email:</strong><a href="mailto:contact@mycompany.com"> contact@mycompany.com</a><br />
      <strong>Website:</strong> <a href="#">www.mycompany.com</a><br />
      <strong>Phone:</strong> 0800-123456 </p>
  </div>