  <div class="left-panel">
    <h1><?=App::xlat('CELL_title')?>
      <span><?=App::xlat('CELL_subtitle')?></span>
    </h1>
    <img height="90" width="670" title="<?=App::xlat('CELL_subtitle')?>" alt="<?=App::xlat('CELL_subtitle')?>" src="<?=App::media('/images/cell.jpg') ?>" />
    <p><?=App::xlat('CELL_pharagraph_1')?></p>
    <br />
    <p><?=App::xlat('CELL_pharagraph_2')?></p>
    <br />
    <p><?=App::xlat('CELL_pharagraph_3')?></p>

    <?php if( ! empty($this->cells) ):?>
      <br />
      <h1 class="no-line"><?=App::xlat('CELL_map_adress_title')?>
        <span><?=App::xlat('CELL_map_adress_subtitle')?></span>
      </h1>

      <?php
        $landlord   = App::xlat('CELL_landlord');
        $leader     = App::xlat('CELL_leader');
        $supervisor = App::xlat('CELL_supervisor');
        $address    = App::xlat('CELL_address');
        $time       = App::xlat('CELL_time');

        foreach($this->cells AS $cell){
          $tabs['tab'][ $cell['zone_id'] ]   = "<li><a href='#'>{$cell['zone']}</a></li>";
          $tabs['panes'][ $cell['zone_id'] ][] =
            "<p class='address'>
               <em><span title='$landlord' class='icons-cell home' /> {$cell['landlord']}</em>
               <em><span title='$address' class='icons-cell address' /> {$cell['address']}</em>
               <em><span title='$time' class='icons-cell time' /> {$cell['hours']}</em>
               <em><span title='$leader' class='icons-cell leader' /> {$cell['leader']}</em>
               <em><span title='$supervisor' class='icons-cell supervisor' /> {$cell['supervisor']}</em>
             </p>";
        }
      ?>

      <ul class="cell">
        <?=implode('',$tabs['tab']);?>
      </ul>

      <div class="panes">
        <?php foreach($tabs['tab'] AS $key=>$tab):?>
          <div class="cell"><?=implode('',$tabs['panes'][$key]);?></div>
        <?php endforeach;?>
      </div>

    <?php endif;?>

  </div>

  <div class="right-panel">
    <?=App::module('Addons')->renderBlock("bible/index","search", array("form_type" => "simple", "location" => "frontend") )?>
    <?=App::module('Addons')->renderBlock("bible/index","phrase")?>
    <?=App::module('Addons')->renderBlock("poll/index","get-poll", array('id'=>'1'));?>
    <?=App::module('Articles')->renderBlock("index","promote", array('past_next'=>'next', 'height'=>'445', 'width'=>'290', 'limit'=>"10", 'category'=>'4' ) );?>
    <?=App::module('Addons')->renderBlock("guestbook/index","latest");?>
  </div>

<?php
/*
$cells
Array(
  [id] => 1
  [landlord] => Bertha De Escobedo
  [address] => Del Valle #635 Casa Blanca
  [phone] => 
  [hours] => Martes 7:30 Pm
  [sector_id] => 1
  [sector] => Sector 1
  [leader] => Hector Mejia
  [supervisor] => Hector Mejia
  [zone_id] => 1
  [zone] => Zona 1
  [shepherd] => Miguel Paez
  [map_cordinates] => 
  [map_image] => default_map.png
  [created] => 2012-08-24 08:30:07
  [updated] => 2012-08-24 08:30:07
  [modified] => 
  [language] => es
  [status] => enabled
 )
 */
?>