
<div class="left-panel">
  <h1><?=App::xlat('CONTACT_title')?><span><?=App::xlat('CONTACT_subtitle')?></span></h1>
  <img height="90" width="670" title="<?=App::xlat('CONTACT_subtitle')?>" alt="<?=App::xlat('CONTACT_subtitle')?>" src="<?=App::media('/images/contact-us.jpg') ?>" />
  <p><?=App::xlat('CONTACT_pharagraph_1')?></p>
  <p><?=App::xlat('CONTACT_pharagraph_2')?></p>

  <div class="contact-form">
    <?php if( empty($this->message_sent) ):?>

      <?php $errors = App::module('Core')->getModel('Form')->get_error_messages($this->form); ?>
      <?php if( ! empty($errors) ):?>
        <ul class='form-errors'>
        <?php foreach($errors AS $error): ?>
          <li><?=$error?></li>
        <?php endforeach; ?>
        </ul>
      <?php endif;?>

      <?=$this->form?>
    <?php else:?>
      <?=App::xlat('CONTACT_message_sent')?>
    <?php endif;?>
  </div>
</div>

<div class="right-panel">
  <?=App::module('Addons')->renderBlock("site/index","get-site-email-manager");?>
  <?=App::module('Addons')->renderBlock("site/index","map",array('zoom'=>15));?>
</div>
