
<?php if($this->exito):?>
  <p>
    <?=App::xlat('PUBLIC_CONTACT_mensaje_enviado')?>
  </p>
<?php endif;?>

<?php if($this->error):?>
  <div class="error-msgbox">
    <?=App::xlat('PUBLIC_CONTACT_error')?>
  </div>
<?php endif;?>



  <div class="left-panel">
    <h1>Send a Message<span>Sed congue, dui vel tristique mollis...</span></h1>
    <p>Ut id mi sed lacus pulvinar luctus eu vitae enim. Phasellus placerat ipsum nec leo porta accumsan. Aliquam dui ante, sagittis ultrices venenatis id, scelerisque consequat lacus. Etiam vehicula, libero non ultricies volutpat, quam lacus consectetur massa, in tempus orci lorem sit amet nisl. Praesent mollis ultrices lacus non tempor. Curabitur congue, nulla non consequat rutrum, tellus tortor aliquet massa, eu tincidunt sem velit ac leo. In rhoncus diam eget nunc lobortis eget interdum augue euismod. </p>
    <p>Proin tempus pulvinar nunc et pulvinar. Maecenas vel sem sit amet mauris porttitor suscipit non id neque. Ut vehicula dui at ante ultricies ac bibendum erat tempus. Mauris sagittis est sed orci pulvinar a lobortis orci lobortis. Aenean non velit sit amet nulla laoreet gravida.</p>
    <h1>Contact Form<span>Sed congue, dui vel tristique mollis...</span></h1>
    <?=$this->form?>
  </div>

  <div class="right-panel">
    <h1>Get in touch<span>Sed congue, dui vel tristique mollis...</span></h1>
    <p><strong>Address Info</strong><br />123 Pine Street<br />Mycity, ST 19000</p>
    <p><strong>Email:</strong><a href="mailto:contact@mycompany.com"> contact@mycompany.com</a><br />
      <strong>Website:</strong> <a href="#">www.mycompany.com</a><br />
      <strong>Phone:</strong> 0800-123456 </p>
  </div>


