  <div class="left-panel">
    <h1>
      <?=$this->doctrine_article['title']?>
      <span><?=App::xlat('CONTENT_subtitle_doctrine')?></span>
    </h1>
    <?= eval('?>' . $this->doctrine_article['article'] . '<?php ');?>
  </div>

  <div class="right-panel">
    <?=App::module('Addons')->renderBlock("site/index","social-networks");?>
    <?=App::module('Articles')->renderBlock("index","promote", array('past_next'=>'next') );?>
  </div>