  <div class="left-panel">
    <h1>
      <?=$this->doctrine_article['title']?>
      <span><?=App::xlat('CONTENT_subtitle_doctrine')?></span>
    </h1>
    <?= eval('?>' . $this->doctrine_article['article'] . '<?php ');?>
  </div>

  <div class="right-panel">
    <?=App::module('Addons')->renderBlock("bible/index","search", array("form_type" => "simple", "location" => "frontend") )?>
    <?=App::module('Addons')->renderBlock("bible/index","phrase")?>
    <?=App::module('Articles')->renderBlock("index","promote", array('past_next'=>'next', 'height'=>'445', 'width'=>'290', 'limit'=>"10", 'category'=>'4' ) );?>
  </div>