<div class="flexar">
  <h1 class="flexar-big">
    <span title="<?=App::xlat('FLEXAR_slogan')?>">
      <?=App::xlat('FLEXAR_slogan')?>
    </span>
  </h1>
  <p><?=App::xlat('FLEXAR_pharagraph_1')?></p>
  <div class="flexar-form">
    <?php if( empty($this->message_sent) ):?>

      <?php $errors = App::module('Core')->getModel('Form')->get_error_messages($this->form); ?>
      <?php if( ! empty($errors) ):?>
        <ul class='form-errors'>
        <?php foreach($errors AS $error): ?>
          <li><?=$error?></li>
        <?php endforeach; ?>
        </ul>
      <?php endif;?>

      <?=$this->form?>
    <?php else:?>
      <?=App::xlat('CONTACT_message_sent')?>
    <?php endif;?>
  </div>

</div>