<div id="ddSlider_container">

  <ul id="ddSlider">
<?php foreach ($this->announcements AS $key=>$announcement): ?>
  <li>
    <a href="<?=App::base( "/{$announcement['article_type_seo']}/{$announcement['seo']}" )?>">
      <img src="<?=App::media( '/articles/' . $announcement['picture'] )?>" alt="" width="100%" height="340" />
    </a>
    <div class="description" ><?=$announcement['title']?></div>
  </li>
<?php endforeach;?>
  </ul>

  <div class="slider_nav">
    <div class="slider_arrow_left"></div>
    <div class="slider_arrow_right"></div>
    <ul class="slider_selector"></ul>
  </div>

</div>
<span class="separator"></span>
<div id="bible_phrase" class="gradient">
  <?=App::module('Addons')->renderBlock("bible/index","phrase")?>
</div>
<span class="separator"></span>

<div class="three-cols gradient">
  <div class="col">
    <h2>
      <?=App::xlat('MAINPAGE_column_join')?>
      <span><?=App::xlat('MAINPAGE_column_join_span')?></span>
    </h2>
    <img src="/media/img_1.jpg" alt="picture" class="none" height="95" width="300" />
    <p class="col_description"><?=App::xlat('MAINPAGE_column_join_description')?></p>
    <p class="right">
      <a href="<?=App::url_translate('LINK_join_us')?>">
        <?=App::xlat('ARTICLE_read_more')?>
      </a>
    </p>
  </div>

  <div class="col">
    <h2>
      <?=App::xlat('MAINPAGE_column_project')?>
      <span><?=App::xlat('MAINPAGE_column_project_span')?></span>
    </h2>
    <img src="/media/img_1.jpg" alt="picture" class="none" height="95" width="300" />
    <p class="col_description"><?=App::xlat('MAINPAGE_column_project_description')?></p>
    <p class="right">
      <a href="<?=App::url_translate('LINK_projects')?>">
        <?=App::xlat('ARTICLE_read_more')?>
      </a>
    </p>
  </div>

  <div class="col last">
    <h2>
      <?=App::xlat('MAINPAGE_column_sermon')?>
      <span><?=App::xlat('MAINPAGE_column_sermon_span')?></span>
    </h2>
    <img src="/media/img_1.jpg" alt="picture" class="none" height="95" width="300" />
    <p class="col_description"><?=App::xlat('MAINPAGE_column_sermon_description')?></p>
    <p class="right">
      <a href="<?=App::url_translate('LINK_preaching')?>">
        <?=App::xlat('ARTICLE_read_more')?>
      </a>
    </p>
  </div>
</div>

<?php 
/*
$announcement
Array
(
    [0] => Array
        (
            [id] => 123
            [article_id] => 135
            [title] => Requisitos del sitio
            [seo] => requisitos-del-sitio
            [created] => 2010-02-01 09:39:31
            [publicated] => 2010-02-01 09:39:31
            [username] => robe@gmail.com
            [autor] => Roberto Mejia
            [written] => 1
            [picture] => 
            [article_type_id] => 4
            [article_type_name] => Anuncios
            [article_type_seo] => anuncios
            [category_id] => 2
            [category_name] => Articulos
            [category_seo] => articulos
            [status] => 1
            [status_name] => Active
            [lang_id] => 1
            [language] => es
            [lang_namespace] => es_MX
            [lang_status] => 1
        )
 */
?>