  <div class="left-panel">
    <h1><?=App::xlat('MINISTERY_title')?>
      <span><?=str_replace("%ref%", App::base( App::xlat('route_bible') . App::xlat('BIBLE_seo_book_acts') . '/6/3'), App::xlat('MINISTERY_subtitle') )?></span>
    </h1>
    <img height="150" width="645" title="<?=App::xlat('MINISTERY_subtitle')?>" alt="<?=App::xlat('MINISTERY_subtitle')?>" src="<?=App::media('/images/ministery.jpg') ?>" />
    <p><?=App::xlat('MINISTERY_pharagraph_1')?></p>
    <p><?=App::xlat('MINISTERY_pharagraph_2')?></p>

  </div>

  <div class="right-panel">
    <h1>A ver que ponemos aqui<span>Sed congue, dui vel tristique mollis...</span></h1>
    <p><strong>Address Info</strong><br />123 Pine Street<br />Mycity, ST 19000</p>
    <p><strong>Email:</strong><a href="mailto:contact@mycompany.com"> contact@mycompany.com</a><br />
      <strong>Website:</strong> <a href="#">www.mycompany.com</a><br />
      <strong>Phone:</strong> 0800-123456 </p>
  </div>