  <h1><?=App::xlat('MINISTERY_title')?>
    <span><?=str_replace("%ref%", App::base( App::xlat('route_bible') . App::xlat('BIBLE_seo_book_acts') . '/6/3'), App::xlat('MINISTERY_subtitle') )?></span>
  </h1>
  <img border="0" width="980" height="90" title="Ministerios de la Iglesia la Misión" alt="Ministerios de la Iglesia la Misión" src="<?=App::media('/images/ministery.jpg')?>" />

  <?= eval('?>' . $this->article['article'] . '<?php ');?>



<?php
/*
 *   

Array
(
    [id] => 174
    [article_id] => 187
    [title] => Ministerios
    [seo] => ministerios
    [created] => 2011-09-16 09:39:31
    [publicated] => 2011-09-16 09:39:31
    [event_date] =>
    [username] => robe@gmail.com
    [author] => Roberto Mejia
    [written] => 1
    [picture] => elias-heidi-paez.jpg
    [article_type_id] => 5
    [article_type_name] => Seccion de pagina
    [article_type_seo] => seccion-de-pagina
    [category_id] => 2
    [category_name] => Articulos
    [category_seo] => articulos
    [status] => enabled
    [status_name] => Active
    [lang_id] => 1
    [language] => es
    [lang_namespace] => es_MX
    [lang_status] => 1
    [addon] => 0
    [article] =>
)
 */
?>
