<?php
  $ds = "/";
?>

<div class="all-panel">
  <div id="bible-book">
    <div class="opened">

      <?=App::module('Addons')->renderBlock("bible/index","options", array("section" => "search", "reset"=>"no") )?>

      <div class="top">
        <div class="t-left"></div> <div class="t-right"></div>
      </div>

      <div class="mid">

        <div class='search-data'>
          <?= empty($this->search['pagination_html']) ? '' : $this->search['pagination_html'];?>
          <?php if( ! empty($this->search['items']) ): ?>

            <?php foreach($this->search['items'] AS $search):?>
              <div class='data'>
                <a href="<?=App::base( App::xlat('route_bible') . $search['seo'] . $ds . $search['cap'] )?>">
                  <?="{$search['book']} {$search['cap']}:{$search['ver']}"?>
                </a>
                <h1><?=$search['texto']?></h1>
              </div>
            <?php endforeach;?>

          <?php else: ?>

            <p> <?=App::xlat('BIBLE_search_nothing_found')?> </p>

          <?php endif; ?>
          <?= empty($this->search['pagination_html']) ? '' : $this->search['pagination_html'];?>
        </div>

      </div>

      <div class="bot">
        <div class="b-left"></div> <div class="b-right"></div>
      </div>
    </div>
  </div>
</div>

<?php
/*
$search
[0] => Array
    (
        [id] => 23168
        [book_id] => 40
        [cap] => 1
        [ver] => 16
        [lang_id] => 1
        [texto] => y Jacob engendró a José, marido de María, de la cual nació Jesús, llamado el Cristo.
        [book] => Mateo
        [seo] => mateo
    )
*/
?>
