
<div class="block bible_chapters_listing">
  <h1 class="no-line">
    <?=App::xlat('BIBLE_chapters_block_topic')?>
    <span><?=App::xlat('BIBLE_chapters_block_subtitle')?></span>
  </h1>
  <form id="chapter-selection" name="chapter-selection" method="post" action="">
    <select multiple >
      <?php foreach($this->chapters AS $chapter): ?>
        <option value="<?=$this->current_book.'/'.$chapter['cap']?>" <?=($this->current_chapter==$chapter['cap']) ? "selected" : false;?> ><?=App::xlat('BIBLE_chapter').' '.$chapter['cap']?></option>
      <?php endforeach;?>
    </select>
  </form>
</div>