<h1 class="no-line">
  <?=App::xlat('BIBLE_block_search')?>
  <span><?=App::xlat('BIBLE_block_search_subtitle')?></span>
</h1>
<img src="<?=App::media('/images/holy-bible.jpg')?>" alt=" <?=App::xlat('BIBLE_block_search_subtitle')?> " title=" <?=App::xlat('BIBLE_block_search_subtitle')?> " class="none" height="95" width="300" />
<form id="bible-search" name="bible-search" method="post" action="<?=App::base( App::xlat('route_bible') )?>buscar">
  <input name="search" type="text" maxlength="30" size="44" />
  <input type="submit" value="buscar" />
</form>
<p class="col_description"><?=str_replace("%bible_url%", '<a href="' . App::url_translate('LINK_bible') .'">'. App::xlat('BREADCRUM_bible') .'</a>', App::xlat('BIBLE_block_search_description'))?></p>
<p class="right">
  <a href="<?=App::url_translate('LINK_bible')?>">
    <?=App::xlat('ARTICLE_go_to_section')?>
  </a>
</p>