<h1 class="no-line">
  <?=App::xlat('OPTION_search')?>
  <span><?=App::xlat('BIBLE_search_intro_subtitle')?></span>
</h1>
<a href="<?=App::url_translate('LINK_bible')?>">
  <img src="<?=App::media('/images/holy-bible.jpg')?>" alt=" <?=App::xlat('OPTION_search')?> " title=" <?=App::xlat('OPTION_search')?> " class="none" height="95" width="300" />
</a>
<?=$this->form?>
<p class="col_description intro"><?=App::xlat('BIBLE_search_intro_description')?></p>
<p class="right">
  <a href="<?=App::url_translate('LINK_bible')?>">
    <?=App::xlat('ARTICLE_go_to_section')?>
  </a>
</p>