<h1 class="no-line">
  <?=App::xlat('BIBLE_block_search')?>
  <span><?=App::xlat('BIBLE_block_search_subtitle')?></span>
</h1>
<img src="<?=App::media('/images/holy-bible.jpg')?>" alt=" <?=App::xlat('BIBLE_block_search_subtitle')?> " title=" <?=App::xlat('BIBLE_block_search_subtitle')?> " class="none" height="95" width="300" />
<?=$this->form?>
<p class="col_description intro"><?=App::xlat('BIBLE_block_search_description')?></p>
<p class="right">
  <a href="<?=App::url_translate('LINK_bible')?>">
    <?=App::xlat('ARTICLE_go_to_section')?>
  </a>
</p>