
<?php if( ! empty($this->article) ): ?>

  <div class="all-panel gradient shepherd-welcome">
    <h1 class="no-line">
      <?=$this->article['title']?>
    </h1>
    <img class="right" src="<?=App::media( '/ministerios/elias-heidi-paez.jpg' )?>" title="<?=App::xlat('shepherd_image_title')?>" alt="<?=App::xlat('shepherd_image_title')?>" height="240" width="240" />
    <?=$this->article['article'].'</p>'?>;
  </div>
  <span class="separator"></span>

<?php endif; ?>

<?php
/*
 $this->article
Array
(
    [id] => 175
    [article_id] => 188
    [title] => Bienvenida
    [seo] => bienvenida
    [article] => Paz de Cristo    
    [email] => 
    [phone] => 
    [address] => 
    [type_id] => 67
    [type] => seccion-pagina
    [type_name] => Seccion de pagina
    [created] => 2012-08-01 13:23:52
    [publicated] => 2012-08-01
    [event_date] => 
    [stop_publication] => 
    [username] => robe@gmail.com
    [author] => Roberto Mejia Bañuelos
    [language] => es
    [written] => 1
    [folder] => 
    [promote] => disabled
    [mobile] => enabled
    [addon] => disabled
    [status] => enabled
)
 */
?>