
<?php if( ! empty($this->coming_next)): ?>
  <?php $core = App::module('Core')->getModel('Dates');?>
  <?php if( App::getDesign()->getCurrentLayout()==="default"): ?>
    <h1>
      <?=App::xlat('EVENTS_coming_soon')?>
    </h1>
  <?php endif;?>

  <div id="slider-content">

    <ul id="slider">
      <?php foreach ($this->coming_next AS $key=>$next_event): ?>
        <li>
          <a href="<?=App::base( App::xlat( $next_event['type'].'_singular' ) ."/". $next_event['seo']  )?>">
            <img src="<?=App::media( $next_event['folder'] . "gallery/slider.jpg" )?>" alt="" width="100%" height="340" />
          </a>
        </li>
      <?php endforeach;?>
    </ul>

  </div>

<?php endif;?>

<?php 
/*
Array
(
    [0] => Array
        (
            [id] => 337
            [article_id] => 194
            [title] => Terminando de trabajar por ahora
            [seo] => terminando-de-trabajar-por-ahora
            [article] =>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ornare, magna sit amet mattis cursus, augue eros malesuada odio, sit amet tincidunt lacus sem in nibh. Nam quis enim sit amet lorem imperdiet tempor. Fusce fermentum dui eget dolor porta gravida. 
            [email] => 
            [phone] => 
            [address] => 
            [type_id] => 69 
            [type] => articulos 
            [type_name] => Articulos 
            [created] => 2013-01-16 18:09:34 
            [publicated] => 2013-01-16 
            [event_date] => 
            [stop_publication] => 
            [username] => robe@gmail.com 
            [author] => Roberto Mejia Bañuelos 
            [language] => es 
            [written] => 1 
            [folder] => /articles/2013/01/194/ 
            [promote] => enabled 
            [mobile] => enabled 
            [addon] => enabled 
            [status] => enabled 
         )
 */
?>