<head>
<meta charset="UTF-8" />
<title><?=isset($this->pageTitle) ? $this->pageTitle:@$this->xd['pageTitle'];?></title>
<meta name="author" content="<?=isset($this->pageAuthor) ? $this->pageAuthor:@$this->xd['pageAuthor'];?>" />
<meta name="copyright" content="<?=isset($this->pageCopyright) ? $this->pageCopyright:@$this->xd['pageCopyright'];?>" />
<meta name="description" content="<?=isset($this->pageDescription) ? $this->pageDescription:@$this->xd['pageDescription'];?>" />
<meta name="keywords" content="<?=isset($this->pageKeywords) ? $this->pageKeywords:@$this->xd['pageKeywords'];?>" />
<meta name="Locality" content="Mazatlan, Mexico" />
<meta name="lang" content="es" />
<meta name="revisit-after" content="7 days" />

<!--Links-->
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/bootstrap/bootstrap-w8.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/font-awesome/css/font-awesome.min.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/frontend-intro.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeJsPath('/nicescroll/jquery.mCustomScrollbar.css')?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/font/stylesheet.css');?>" rel="stylesheet" />

    <!--[if IE 7]
      <link href="<?=App::getDesign()->getRelativeSkinPath('/css/font-awesome/css/font-awesome-ie7.min.css');?>" rel="stylesheet" />
    [endif]-->

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,300,600' rel='stylesheet' type='text/css'>

	<?= App::header()->getLinks();?>

	<?=@$this->xd['_block']['links'];?>

<!--Scripts-->
  <!--[if IE]>
    <script src="<?=App::getDesign()->getRelativeJsPath('/html5.js','js');?>"></script>
  <![endif]-->
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery-1.8.0.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery-ui/jquery-ui-1.9.1.custom.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/bootstrap/bootstrap.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery.mousewheel.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/nicescroll/jquery.mCustomScrollbar.min.js','js');?>" ></script>

    <script>
        var baseUrl="<?=App::base();?>";
        var wwwUrl="<?=App::www();?>";
        var skinUrl="<?=App::skin();?>";
        var jsUrl="<?=App::url()->get('','js');?>";
        var jslibUrl="<?=App::url()->get('','jslib');?>";
        var curLang="<?=App::locale()->getLang();?>";
        var skinRelative = "<?=App::getDesign()->getRelativeSkinPath()?>";
        var jsRelative = "<?=App::getDesign()->getRelativeJsPath()?>";
        var jsLibRelative = "<?=App::getDesign()->getRelativeJsPath("","jslib")?>";

        jQuery(document).ready(function(){
          <?=App::header()->get_jquery_events();?>

          jQuery('.main div.span3').mouseenter(function(){
            $(this).css({'border-bottom':'4px solid #00B1EB','cursor':'pointer'});
            $(this).find("i").css({color:'#75D5F4'});
            $(this).find("h1").css({'border-bottom':'1px solid #00B1EB'});
            $(this).find("a").css({'color':'#fff'});
          }).mouseleave(function() {
            $(this).css({'border-bottom':'4px solid #ccc'});
            $(this).find("i").css({color:'#00B1EB'});
            $(this).find("h1").css({'border-bottom':'1px solid #ccc'});
            $(this).find("a").css({'color':'#787878'});
          });

          jQuery('.main div.span3,.main div.span3 p,.main div.span3 h1').click(function(){
            window.location = $(this).find("h1 a").attr('href');
          });

          jQuery('footer .scroll-this').mCustomScrollbar({set_height:'100%'});
          
        });
    </script>

		<script id="img-wrapper-tmpl" type="text/x-jquery-tmpl">	
			<div class="rg-image-wrapper fit-to-design">
				<div class="rg-caption-wrapper">
					<div class="rg-caption" style="display:none;">
						<p></p>
					</div>
				</div>
				{{if itemsCount > 1}}
					<div class="rg-image-nav">
						<a href="#" class="rg-image-nav-prev">Previous Image</a>
						<a href="#" class="rg-image-nav-next">Next Image</a>
					</div>
				{{/if}}
				<div class="rg-image"></div>
				<div class="rg-loading"></div>
			</div>
		</script>

	<?=App::header()->getScripts();?>

	<?=@$this->xd['_block']['scripts'];?>

	<?=@$this->xd['_block']['add'];?>

	<?=App::header()->getCode();?>

</head>