<div class="block social_networks">
  <h1>
    <?=App::xlat('CONTACT_SOCIAL_NETWORKS_title')?>
    <span><?=App::xlat('CONTACT_SOCIAL_NETWORKS_subtitle')?></span>
  </h1>

  <h2>
    <a class="facebook" href="<?=App::getConfig('url_facebook')?>"> <?=App::xlat('HEADER_follow_us_facebook')?> </a>
  </h2>

  <h2>
    <a class="twitter" href="<?=App::getConfig('url_twitter')?>"> <?=App::xlat('HEADER_follow_us_twitter')?> </a>
  </h2>

  <h2>
    <a class="youtube" href="<?=App::getConfig('url_youtube')?>"> <?=App::xlat('HEADER_follow_us_youtube')?> </a>
  </h2>

  <h2>
    <a class="gplus" href="<?=App::getConfig('url_google')?>"> <?=App::xlat('HEADER_follow_us_gplus')?> </a>
  </h2>

</div>