  <div class="left-panel">
    <h1>
      <?=$this->fraternity['title']?>
      <span><?=App::xlat('CONTENT_subtitle_fraternities')?></span>
    </h1>
    <?= eval('?>' . $this->fraternity['article'] . '<?php ');?>
  </div>

  <div class="right-panel">
    <h1>A ver que ponemos aqui<span>Sed congue, dui vel tristique mollis...</span></h1>
    <p><strong>Address Info</strong><br />123 Pine Street<br />Mycity, ST 19000</p>
    <p><strong>Email:</strong><a href="mailto:contact@mycompany.com"> contact@mycompany.com</a><br />
      <strong>Website:</strong> <a href="#">www.mycompany.com</a><br />
      <strong>Phone:</strong> 0800-123456 </p>
  </div>
