<head>
<meta charset="UTF-8" />
<title><?=isset($this->pageTitle) ? $this->pageTitle:@$this->xd['pageTitle'];?></title>
<meta name="author" content="<?=isset($this->pageAuthor) ? $this->pageAuthor:@$this->xd['pageAuthor'];?>" />
<meta name="copyright" content="<?=isset($this->pageCopyright) ? $this->pageCopyright:@$this->xd['pageCopyright'];?>" />
<meta name="description" content="<?=isset($this->pageDescription) ? $this->pageDescription:@$this->xd['pageDescription'];?>" />
<meta name="keywords" content="<?=isset($this->pageKeywords) ? $this->pageKeywords:@$this->xd['pageKeywords'];?>" />
<meta name="Locality" content="Mazatlan, Mexico" />
<meta name="lang" content="es" />
<meta name="revisit-after" content="7 days" />

<!--Links-->
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/reset.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/frontend.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/menus.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/columns.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/forms.css');?>" rel="stylesheet" />

	<!-- ieHacks -->
		<!--[if lt IE 7]>
			<link href="<?=App::getDesign()->getRelativeSkinPath('/css/ie/ie.css');?>" rel="stylesheet" />
		<![endif]-->

		<!--[if lt IE 6]>  <![endif]-->
		<!--[if lt IE 7]>  <![endif]-->
		<!--[if lt IE 8]>  <![endif]-->

	<?= App::header()->getLinks();?>

	<?=@$this->xd['_block']['links'];?>

<!--Scripts-->
  <!--[if IE]>
    <script src="<?=App::getDesign()->getRelativeJsPath('/html5.js','js');?>"></script>
  <![endif]-->
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery-1.8.0.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/shared_methods.js','js');?>" ></script>

    <script>
        var baseUrl="<?=App::base();?>";
        var wwwUrl="<?=App::www();?>";
        var skinUrl="<?=App::skin();?>";
        var jsUrl="<?=App::url()->get('','js');?>";
        var jslibUrl="<?=App::url()->get('','jslib');?>";
        var curLang="<?=App::locale()->getLang();?>";
        var skinRelative = "<?=App::getDesign()->getRelativeSkinPath()?>";
        var jsRelative = "<?=App::getDesign()->getRelativeJsPath()?>";
        var jsLibRelative = "<?=App::getDesign()->getRelativeJsPath("","jslib")?>";

        jQuery(document).ready(function(){

          <?php if( isset($this->current_main_menu) ):?>
            jQuery("ul#menu li:eq(<?=$this->current_main_menu?>) a").contents().unwrap().wrap("<span>").parent().addClass("icons active");
          <?php endif;?>

          <?php if( ! empty($this->set_bible_options_position) ):?>
            set_element_position('div.opened', bible.dom.opt_options,1);
          <?php endif;?>
          });
    </script>

	<?=App::header()->getScripts();?>

	<?=@$this->xd['_block']['scripts'];?>

	<?=@$this->xd['_block']['add'];?>

	<?=App::header()->getCode();?>

</head>