<head>
<meta charset="UTF-8" />
<title><?=isset($this->pageTitle) ? $this->pageTitle:@$this->xd['pageTitle'];?></title>
<meta name="author" content="<?=isset($this->pageAuthor) ? $this->pageAuthor:@$this->xd['pageAuthor'];?>" />
<meta name="copyright" content="<?=isset($this->pageCopyright) ? $this->pageCopyright:@$this->xd['pageCopyright'];?>" />
<meta name="description" content="<?=isset($this->pageDescription) ? $this->pageDescription:@$this->xd['pageDescription'];?>" />
<meta name="keywords" content="<?=isset($this->pageKeywords) ? $this->pageKeywords:@$this->xd['pageKeywords'];?>" />
<meta name="Locality" content="Mazatlan, Mexico" />
<meta name="lang" content="es" />
<meta name="revisit-after" content="7 days" />

<!--Links-->
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/bootstrap/bootstrap-w8.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/font-awesome/css/font-awesome.min.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/frontend-intro.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/css/frontend-inner.css');?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeJsPath('/nicescroll/jquery.mCustomScrollbar.css')?>" rel="stylesheet" />
    <link href="<?=App::getDesign()->getRelativeSkinPath('/font/stylesheet.css');?>" rel="stylesheet" />

    <!--[if IE 7]
      <link href="<?=App::getDesign()->getRelativeSkinPath('/css/font-awesome/css/font-awesome-ie7.min.css');?>" rel="stylesheet" />
    [endif]-->

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,400,300,600' rel='stylesheet' type='text/css'>

	<?= App::header()->getLinks();?>

	<?=@$this->xd['_block']['links'];?>

<!--Scripts-->
  <!--[if IE]>
    <script src="<?=App::getDesign()->getRelativeJsPath('/html5.js','js');?>"></script>
  <![endif]-->
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery-1.8.0.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery-ui/jquery-ui-1.10.1.custom.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/bootstrap/bootstrap.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/jquery.mousewheel.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/nicescroll/jquery.mCustomScrollbar.min.js','js');?>" ></script>
    <script src="<?=App::getDesign()->getRelativeJsPath('/shared_methods.js','js');?>" ></script>

    <script>
        var baseUrl="<?=App::base();?>";
        var wwwUrl="<?=App::www();?>";
        var skinUrl="<?=App::skin();?>";
        var jsUrl="<?=App::url()->get('','js');?>";
        var jslibUrl="<?=App::url()->get('','jslib');?>";
        var curLang="<?=App::locale()->getLang();?>";
        var skinRelative = "<?=App::getDesign()->getRelativeSkinPath()?>";
        var jsRelative = "<?=App::getDesign()->getRelativeJsPath()?>";
        var jsLibRelative = "<?=App::getDesign()->getRelativeJsPath("","jslib")?>";

        jQuery(document).ready(function(){

          <?php if( isset($this->current_main_menu) ):?>
            // jQuery("ul#menu li:eq(<?=$this->current_main_menu?>) a").contents().unwrap().wrap("<span>").parent().addClass("icons active");
          <?php endif;?>

          <?php if( ! empty($this->set_bible_options_position) ):?>
            set_element_position('div.opened', bible.dom.opt_options,1);
          <?php endif;?>

          jQuery('footer .scroll-this').mCustomScrollbar({set_height:'100%'});
          

          <?=App::header()->get_jquery_events();?>

        });
    </script>

	<?=App::header()->getScripts();?>

	<?=@$this->xd['_block']['scripts'];?>

	<?=@$this->xd['_block']['add'];?>

	<?=App::header()->getCode();?>

</head>