
  <div class="left-panel">
    <h1 class="title no-line"><?=$this->article['title']?></h1>
    <h4 class="publicated_at"><?=str_replace( array("%written-date%", "%author%" ), array(App::locale()->toDate(date('Y-m-d'),'long'), $this->article['author']), App::xlat('ARTICLE_PREVIEW_written_by_at'))?></h4>

    <?php if( file_exists( $this->folders['gallery'].DS.'article.jpg' ) ): ?>
      <img src="<?=App::media( $this->article['folder'].'gallery/article.jpg')?>" width="640" height="360" alt="<?=$this->article['title']?>" title="<?=$this->article['title']?>" />
    <?php else: ?>
      <img src="<?=App::media( '/images/article-preview.jpg')?>" width="640" height="360" alt="<?=$this->article['title']?>" title="<?=$this->article['title']?>" />
    <?php endif;?>

    <?php if( ! empty($this->addons) ): ?>
      <ul id="addon-list">
        <?php foreach($this->addons AS $key=>$addon): ?>

          <?php if( ! array_key_exists('id', $addon) ): ?>
              <li>
                <a href="#"><?=$key?></a>
                <ul class="rounder-bot">
                  <?php foreach($addon AS $child_addon): ?>
                    <li>
                      <?=get_addon_link($child_addon['type'],$child_addon['reference'],$child_addon['description'],$child_addon['class'],$child_addon['article_id'],$this->article['created'])?>
                    </li>
                  <?php endforeach;?>
                </ul>
              </li>
          <?php else: ?>

              <?php if( $key=='map' ): ?>
                <li class='map-addon'><a class='map-addon' href="#">Map</a>
                  <ul class="rounder-bot">
                    <li>
                      <?=App::module('Addons')->renderBlock("addon/index","google-map", array('id'=>'article-map','launcher'=>'li.map-addon','coordinates'=>$addon['reference'] ) );?>
                    </li>
                  </ul>
                </li>
              <?php else: ?>
                <li><a href="#">Gallery</a>
                  <ul class="rounder-bot">
                    <li>
                      <?=App::module('Addons')->renderBlock("addon/index","mini-gallery", array( 'path'=>$this->folders['url'], 'thumb'=>$this->folders['thumb'] ) );?>
                    </li>
                  </ul>
                </li>
              <?php endif; ?>

          <?php endif; ?>
        <?php endforeach;?>
      </ul>
    <?php endif;?>

    <?=$this->article['article']?>

  </div>

<div class="right-panel">
  <?=App::module('Addons')->renderBlock("rating/index","get-rating", array('id' => $this->article['article_id']))?>
  <?=App::module('Addons')->renderBlock("poll/index","get-poll", array('id'=>'1') );?>
</div>

  <?=App::module('Addons')->renderBlock("comments/index","get-comments", array('id' => $this->article['article_id'], 'type' => 'article' ))?>
  
  
<?php 
/*
 * @todo: coderefactor
 */

 function get_addon_link($type=null,$reference=null,$description=null,$class=null,$id=null,$created=null){
   switch($type){
     case 'link':
       return "<a href='$reference' target='".(($class=='exlink')? '_blank':'_self')."' > $description </a>";
       break;
     case 'video':
       return "<a href='http://www.youtube.com/v/$reference?rel=0&wmode=transparent&autoplay=1&showinfo=0' class='cBox_youtube' > $description </a>";
       break;
     case 'audio':
     case 'files':
     case 'gallery':
       $url=App::base( 'download/'.strtotime($created).'/'.$type.'/'.$id.'/'.$reference );
       return "<a href='$url'> $reference </a>";
       break;
   }

 }

?>