<div class="left-panel">
  <h1>
    <?=$this->doctrine_detail['title']?>
    <span><?=App::xlat('CONTENT_subtitle_doctrine')?></span>
  </h1>
  <img height="150" width="645" title="<?=$this->doctrine_detail['title']?>" alt="<?=$this->doctrine_detail['title']?>" src="<?=App::media('/articles/' . App::module('Core')->getModel('Dates')->toDate(8, $this->doctrine_detail['publicated']) ."/". $this->doctrine_detail['picture'] ) ?>">
  <?= eval('?>' . $this->doctrine_detail['article'] . '<?php ');?>
</div>

<div class="right-panel">
  <h1>A ver que ponemos aqui<span>Sed congue, dui vel tristique mollis...</span></h1>
  <p><strong>Address Info</strong><br />123 Pine Street<br />Mycity, ST 19000</p>
  <p><strong>Email:</strong><a href="mailto:contact@mycompany.com"> contact@mycompany.com</a><br />
    <strong>Website:</strong> <a href="#">www.mycompany.com</a><br />
    <strong>Phone:</strong> 0800-123456 </p>
</div>

<?php 
/*
  $this->doctrine_detail
  
Array
(
    [id] => 144
    [article_id] => 157
    [title] => Espíritu Santo
    [seo] => espiritu-santo
    [created] => 2010-02-01 09:39:31
    [publicated] => 2010-02-01 09:39:31
    [username] => robe@gmail.com
    [autor] => Roberto Mejia
    [written] => 1
    [picture] => d.jpg
    [article_type_id] => 5
    [article_type_name] => Seccion de pagina
    [article_type_seo] => seccion-de-pagina
    [category_id] => 2
    [category_name] => Articulos
    [category_seo] => articulos
    [status] => 1
    [status_name] => Active
    [lang_id] => 1
    [language] => es
    [lang_namespace] => es_MX
    [lang_status] => 1
    [article] => 

 */

?>