
<div class="gallery">
  <ul>
  <?php foreach($this->gallery['thumbnails'] AS $image): ?>
    <li>
      <a class="cBox" href="<?=App::media( '/images/gallery/' . $this->gallery['path'] . '/' . $image );?>">
	      <img width="144" height="90" title="" alt="" src="<?=App::media( '/images/gallery/'. $this->gallery['path'] .'/thumbnails/'. $image );?>" />
      </a>
    </li>
  <?php endforeach;?>
  </ul>
</div>

<?php
/*
colorbox usage
$("a.class").colorbox({rel:'class'});

gallery
Array
(
    [thumbnails] => Array
        (
            [0] => evento-iglesia-la-mision-agosto-2010-150_003.jpg
            [1] => evento-iglesia-la-mision-agosto-2010-150_015.jpg
            [2] => evento-iglesia-la-mision-agosto-2010-150_004.jpg
            [3] => evento-iglesia-la-mision-agosto-2010-150_008.jpg
        )
    [path] => 2010/08/150
 */
?>