
  <div id='breadcrumbs'>
  	<ul>
  		<?php if (count((array)$this->pageBreadcrumbs) ):?>
  			<li class='icons breadcrums_home'><a href='<?=App::base("/")?>'><?=App::xlat('BREADCRUM_home');?></a></li>
  			<?php foreach ((array)$this->pageBreadcrumbs as $breadcrumb):?>
  				<li class='icons breadcrum'>
  					<?php if ( empty($breadcrumb['url']) ): ?>
  						<?=$breadcrumb['title']?>
  					<?php else:?>
              <a href='<?=$breadcrumb['url']?>' ><?=$breadcrumb['title']?></a>
  					<?php endif;?>
  				</li>
  			<?php endforeach;?>
  		<?php endif;?>
  	</ul>
  </div>
