<?php if ( ! empty($this->pageBreadcrumbs['title']) ):?>
  <div class="breadcrumbs<?=empty($this->pageBreadcrumbs['crumbs']) ? null : ' has-crumbs'?><?=empty($this->small_bread) ? null : ' small-crumbs'?>">
    <div class="container fit-to-design">

      <?php if( ! empty($this->pageBreadcrumbs['crumbs']) ): ?>
        <?php foreach($this->pageBreadcrumbs['crumbs'] AS $crumb): ?>
          <h1> <span class="<?=$crumb['ico']?>"></span> <a href="<?=App::base($crumb['url'])?>"> <?=$crumb['txt']?> </a> </h1> <span class="icon-chevron-right"></span>
        <?php endforeach;?>
      <?php endif;?>

      <h1> <?=empty($this->pageBreadcrumbs['icon'])?null:'<i class="'. $this->pageBreadcrumbs['icon'] .'"></i>'?>  <?=ucfirst($this->pageBreadcrumbs['title'])?> </h1>

    </div>
  </div>
<?php endif;?>