<?php $menus = explode(",", App::getConfig('main_menu')); $iterator=1; ?>

<?php if ( App::getDesign()->getCurrentLayout() === "default" ) :?>
  <div id="header_container" class="gradient">
<?php endif; ?>

  <div id="header" <?=(App::getDesign()->getCurrentLayout()==="intro") ? 'class="intro gradient"':'';?> >

    <ul id="menu" <?=(App::getDesign()->getCurrentLayout()==="intro") ? 'class="gradient"' : 'class="main_menu"';?>>

  	<?php foreach($menus AS $menu): ?>
          <li <?= (sizeof($menus)==$iterator) ? 'class="last_link"':''; ?><?= ($iterator==1) ? 'class="first_link"':'' ?>>
            <a href="<?=App::url_translate( "LINK_$menu" )?>" <?=(App::getDesign()->getCurrentLayout()==="default") ? 'class="icons"':'';?>>
              <?=App::xlat("MENU_$menu")?>
            </a>
          </li>
  	<?php
          $iterator+=1;
          endforeach; ?>
    </ul>
    <div id="logo_follow_container">
      <h1 class="logo">
        <a href="<?=App::base()?>"><?=App::xlat('HEADER_LOGO_ALT')?></a>
        <span><?=App::xlat('HEADER_site_logo_slogan')?></span>
      </h1>

      <div class="<?=(App::getDesign()->getCurrentLayout()==="intro") ? 'social_networks' : 'bible_phrase default_phrase';?>">
        <? if (App::getDesign()->getCurrentLayout()==="intro"):?>
  
          <ul id="follow_us">
            <li>
              <a href="<?=App::getConfig('url_facebook')?>" class="social facebook" title="<?=App::xlat('HEADER_follow_us_facebook')?>">
                <?=App::xlat('HEADER_follow_us_facebook')?>
              </a>
            </li>
            <li>
              <a href="<?=App::getConfig('url_twitter')?>" class="social twitter" title="<?=App::xlat('HEADER_follow_us_twitter')?>">
                <?=App::xlat('HEADER_follow_us_twitter')?>
              </a>
            </li>
            <li>
              <a href="<?=App::getConfig('url_youtube')?>" class="social youtube" title="<?=App::xlat('HEADER_follow_us_youtube')?>">
                <?=App::xlat('HEADER_follow_us_youtube')?>
              </a>
            </li>
            <li>
              <a href="<?=App::getConfig('url_google')?>" class="social googleplus" title="<?=App::xlat('HEADER_follow_us_gplus')?>">
                <?=App::xlat('HEADER_follow_us_gplus')?>
              </a>
            </li>
    	  </ul>
  
        <?php else:?>
          <?=App::module('Addons')->renderBlock("bible/index","phrase")?>
        <?php endif;?>
      </div>

    </div>

  <?php if ( App::getDesign()->getCurrentLayout() === "default" ) :?>
    </div>
  <?php endif; ?>

</div>

<div class="clr"></div>
<div id="content" class="gradient">
