<!-- Cierre del CONTENT abierto en el HEADER-->
</div>
<div class="clr"></div>
<div id="footer">

<div class="f_top">
<div class="f_top_resize">
<div class="blog">
<h2><?=App::xlat('FOOTER_menu_topic_important_links')?></h2>
<ul>
<li><a href="<?=App::url_translate('LINK_sitemap')?>"><?=App::xlat('FOOTER_link_sitemap')?></a></li>
<li><a href="<?=App::url_translate('LINK_privacy_policy')?>"><?=App::xlat('FOOTER_link_privacy_policy')?></a></li>
<li><a href="<?=App::url_translate('LINK_terms_conditions')?>"><?=App::xlat('FOOTER_link_terms_conditions')?></a></li>
</ul>
</div>

<div class="blog">
<h2><?=App::xlat('FOOTER_menu_topic_fraternities')?></h2>
<ul>
<li><a href="<?=App::url_translate('LINK_fraternities_men')?>"><?=App::xlat('FOOTER_link_fraternities_men')?></a></li>
<li><a href="<?=App::url_translate('LINK_fraternities_women')?>"><?=App::xlat('FOOTER_link_fraternities_women')?></a></li>
<li><a href="<?=App::url_translate('LINK_fraternities_young')?>"><?=App::xlat('FOOTER_link_fraternities_young')?></a></li>
<li><a href="<?=App::url_translate('LINK_fraternities_teens')?>"><?=App::xlat('FOOTER_link_fraternities_teens')?></a></li>
<li><a href="<?=App::url_translate('LINK_fraternities_kids')?>"><?=App::xlat('FOOTER_link_fraternities_kids')?></a><br>
</li>
</ul>
</div>


<div class="blog">
<h2><?=App::xlat('FOOTER_menu_topic_fast_recomend')?></h2>
<p>
<ul>
  <li>  <a href="http://www.antesdelfin.com">Antes del fin</a>  </li>
  <li>  <a href="http://www.antesdelfin.com">Antes del fin</a>  </li>
  <li>  <a href="http://www.antesdelfin.com">Antes del fin</a>  </li>
  <li>  <a href="http://www.antesdelfin.com">Antes del fin</a>  </li>
  <li>  <a href="http://www.antesdelfin.com">Antes del fin</a>  </li>
</ul>
</p>
</div>

<div class="blog last">
<h2><?=App::xlat('FOOTER_menu_topic_fast_contact')?></h2>
<p>
<?=App::xlat('ADDRESS_street')?><br>
<?=App::xlat('ADDRESS_section')?><br />
<?=App::xlat('ADDRESS_city_state')?><br />
<?=App::xlat('ADDRESS_hours')?><br />
<?=App::xlat('ADDRESS_phone')?><br />
<a href="mailto:contacto@iglesialamision.mx">
<?=App::xlat('ADDRESS_mail')?>
</a>
</p>
</div>


<div class="clr"></div>
</div>
</div>


<div class="f_bottom">
<div class="f_b_container">
<p class="leftt">&copy; <a href="<?=App::url_translate()?>"><?=App::getConfig('website_name')?></a> <?=date('Y')?>. All Rights Reserved </p>
<h1 class="flexar"><a href="<?=App::xlat('FOOTER_AUTHOR_URL')?>" target="_blank" title="<?=App::xlat('FOOTER_LOGO_ALT')?>"><?=App::xlat('FOOTER_AUTHOR_BY')?> <?=App::xlat('FOOTER_AUTHOR_TEXT')?></a></h1>
</div>
<div class="clr"></div>
</div>

</div>