  </div>
</div>
<div class="separator-fix">
  <span class="separator_down margin-bottom-20"> </span>
</div>

<div class="clr"></div>
<div id="footer">

<div class="f_top">
<div class="f_top_resize">
<div class="blog">
  <h1><?=App::xlat('FOOTER_menu_topic_important_links')?></h1>
  <ul>
    <li><a href="<?=App::url_translate('LINK_site_requirements')?>"><?=App::xlat('FOOTER_link_site_requirements')?></a></li>
    <li><a href="<?=App::url_translate('LINK_sitemap')?>"><?=App::xlat('FOOTER_link_sitemap')?></a></li>
    <li><a href="<?=App::url_translate('LINK_terms_conditions')?>"><?=App::xlat('FOOTER_link_terms_conditions')?></a></li>
  </ul>
</div>

<div class="blog">
  <h1><?=App::xlat('FOOTER_menu_topic_fast_recomend')?></h1>
  <ul>
    <li>  <a href="http://www.asambleaapostolicamexico.com" target="blank">Asamblea Apostólica México</a>  </li>
    <li>  <a href="http://www.shammahlarevista.com" target="blank">Shammah: La revista</a>  </li>
    <li>  <a href="http://www.lavoz.org" target="blank">La voz de la esperanza</a>  </li>
    <li>  <a href="http://www.antesdelfin.com" target="blank">Antes del fin</a>  </li>
  </ul>
</div>

<div class="blog operation-hours">
  <h1><?=App::xlat('CONTACT_OPERATION_HOURS_title')?></h1>
  <strong> <?=App::xlat('dates_long_day_1')?> </strong>
  <ul>
    <li><?=App::xlat('OPERATION_HOURS_MONDAY_leader')?></li>
    <li><?=App::xlat('OPERATION_HOURS_MONDAY_pray')?></li>
  </ul>

  <strong> <?=App::xlat('dates_long_day_6')?> </strong>
  <ul>
    <li><?=App::xlat('OPERATION_HOURS_SATURDAY_children_class')?></li>
    <li><?=App::xlat('OPERATION_HOURS_SATURDAY_teens_class')?></li>
    <li><?=App::xlat('OPERATION_HOURS_SATURDAY_youth_meeting')?></li>
  </ul>

  <strong> <?=App::xlat('OPERATION_HOURS_SUNDAY_service')?> </strong>
  <ul>
    <li><?=App::xlat('OPERATION_HOURS_SUNDAY_morning')?></li>
    <li><?=App::xlat('OPERATION_HOURS_SUNDAY_afternoon')?></li>
    <li><?=App::xlat('OPERATION_HOURS_SUNDAY_evening')?></li>
  </ul>

</div>

<div class="blog last">
  <h1><?=App::xlat('FOOTER_menu_topic_fast_contact')?></h1>
  <p>
    <?=App::xlat('ADDRESS_street')?><br>
    <?=App::xlat('ADDRESS_section')?><br />
    <?=App::xlat('ADDRESS_city_state')?><br /><br />
    <?=App::xlat('ADDRESS_office')?><br />
    <?=App::xlat('ADDRESS_hours')?><br />
    <?=App::xlat('ADDRESS_phone_1')?><br />
    <?=App::xlat('ADDRESS_phone_2')?><br />
  <a href="<?=App::base( "/" . App::xlat('LINK_contact') )?>">
    <img src="<?=App::skin('/art/icons/mail.png') ?>" alt="" title="" />
  </a>
  </p>
</div>


<div class="clr"></div>
</div>
</div>


<div class="f_bottom">
<div class="f_b_container">
<p class="leftt">&copy; <a href="<?=App::url_translate()?>"><?=App::getConfig('website_name')?></a> <?=date('Y')?>. All Rights Reserved </p>
<h1 class="flexar"><a href="<?=App::base( DS . App::xlat('LINK_flexar') )?>" title="<?=App::xlat('FLEXAR_slogan')?>"><?=App::xlat('FLEXAR_slogan')?></a></h1>
</div>
<div class="clr"></div>
</div>

</div>