<?php $menus = array('about','doctrine','events','fraternities','contact','bible'); $iterator=1; ?>

<?php if ( App::getDesign()->getCurrentLayout() === "default" ) :?>
  <div id="header_container" class="gradient">
<?php endif; ?>

  <div id="header" <?=(App::getDesign()->getCurrentLayout()==="intro") ? 'class="intro gradient"':'';?> >

    <ul id="menu" <?=(App::getDesign()->getCurrentLayout()==="intro") ? 'class="gradient"' : 'class="main_menu"';?>>

  	<?php foreach($menus AS $menu): ?>
          <li <?= (sizeof($menus)==$iterator) ? 'class="last_link"':''; ?><?= ($iterator==1) ? 'class="first_link"':'' ?>>
            <a href="<?=App::url_translate( "LINK_$menu" )?>" <?=(App::getDesign()->getCurrentLayout()==="default") ? 'class="icons"':'';?>>
              <?=App::xlat("MENU_$menu")?>
            </a>
          </li>
  	<?php
          $iterator+=1;
          endforeach; ?>
    </ul>
    <div id="logo_follow_container">
      <h1 class="logo">
        <a href="<?=App::base("/")?>"><?=App::xlat('HEADER_LOGO_ALT')?></a>
        <span><?=App::xlat('HEADER_site_logo_slogan')?></span>
      </h1>

      <div class="social_networks">
    	  <ul id="follow_us">
    	    <li class="icons">
    	      <a href="http://www.facebook.com/iglesialamision" class="icons facebook" title="<?=App::xlat('HEADER_follow_us_facebook')?>">
    	        <?=App::xlat('HEADER_follow_us_facebook')?>
    	      </a>
    	    </li>
          <li class="icons">
            <a href="http://www.twitter.com/iglesialamision" class="icons twitter" title="<?=App::xlat('HEADER_follow_us_twitter')?>">
              <?=App::xlat('HEADER_follow_us_twitter')?>
            </a>
          </li>
          <li class="icons">
            <a href="http://plus.google.com/iglesialamision" class="icons googleplus" title="<?=App::xlat('HEADER_follow_us_gplus')?>">
              <?=App::xlat('HEADER_follow_us_gplus')?>
            </a>
          </li>
          <li class="icons">
            <a href="http://www.youtube.com/iglesialamision" class="icons youtube" title="<?=App::xlat('HEADER_follow_us_youtube')?>">
              <?=App::xlat('HEADER_follow_us_youtube')?>
            </a>
          </li>
    	  </ul>
      </div>

    </div>

  <?php if ( App::getDesign()->getCurrentLayout() === "default" ) :?>
    </div>
  <?php endif; ?>

</div>

<div class="clr"></div>
<div id="content">
