Listado de anuncios >>
<br /><br /><br />

Probando el DATAFILTER
<form name="p" method="#">
		<table border="1" width="100%">
			<tr class='datafilter <?=$this->datafilter->isActive() ? "datafilter-active":null?>'>
				<th width="10"><?=$this->datafilter->field('id')->render();?></th>
			</tr>
			<tr>
						<td class='actions datafilter-buttons'>
							<div class='cui-buttonset cui-buttonset-multi'>
								<?=$this->datafilter->render(App::xlat("Buscar"),"cui-button ui-state-default ui-corner-left cui-button-icon-solo","ui-icon ui-icon-search","gestorCategoriaProductos.listadoRefrescar(url);return false;");?>
								<a class="cui-button ui-state-default ui-corner-right cui-button-icon cui-button-icon-solo <?=($this->datafilter->isActive()) ? null:"ui-state-disabled"?>" href='' onclick='gestorCategoriaProductos.listadoRefrescar("<?=$this->datafilter->getBaseurl()?>");return false;'>
									<span class="ui-icon ui-icon-close"/>
									<?=App::xlat("Limpiar")?>
								</a>
							</div>
						</td>
				</tr>
		</table>
		<input type="submit">
</form>

Probando el DATASORTER
		<table border="1" width="100%">
			<tr>
				<th width="10"><?=$this->datasorter->renderField('id');?><?=App::xlat("id field")?></th>
				<th width="60"><?=$this->datasorter->renderField('autor');?><?=App::xlat("autor field")?></th>
				<th width="60"><?=$this->datasorter->renderField('created');?><?=App::xlat("created field")?></th>
			</tr>
		</table>

<br /><br /><br />									
<?= $this->articles['pagination_html'] ?>

<?php
// baja-opcionez 
echo "<pre>"; print_r( $this->articles ); echo "</pre>";
?>