  <?=App::module('Articles')->renderBlock("index","coming-next", array("category" => App::module("Articles")->getConfig('core','article_type_event_id'), "past_next"=>"next" ) )?>
  <h1>
    <?=App::xlat('EVENTS_past')?>
  </h1>

  <div class="events all-panel">

    <?php if( ! empty($this->events['items']) ):?>
      <?= empty($this->events['pagination_html']) ? '' : $this->events['pagination_html'] ?>
      <?php $core = App::module('Core')->getModel('Dates');?>
      <?php foreach( $this->events['items'] AS $event ): ?>
        <div class="block">
          <h2 class="no-line strong">
            <?=$event['title']?>
            <span><?=App::locale()->toDate($event['publicated'],'long')?></span>
          </h2>
          <a href="<?=App::base( App::xlat('route_events').$event['seo'] )?>">
            <img src="<?=App::media( $this->gallery_path . $core->toDate(8, $event['publicated']) ."/". $event['article_id'] ."/". $event['seo']. "_listing.jpg" ) ?>" width="295" height="95" alt="<?=$event['title']?>" title="<?=$event['title']?>" />
          </a>
          <p><?=$event['description']?></p>
        </div>
      <?php endforeach; ?>
      <?= empty($this->events['pagination_html']) ? '' : $this->events['pagination_html'] ?>

    <?php else:?>
      <h3 class="no-line empty-listing"> <?=App::xlat('LISTING_no_data_found')?> </h3>
    <?php endif;?>

  </div>

<?php
/*
    [items] => Array
        (
            [0] => Array
                (
                    [id] => 143
                    [article_id] => 156
                    [title] => Articulo de prueba # 156
                    [seo] => probando-6
                    [created] => 2010-02-01 09:39:31
                    [publicated] => 2010-02-01 09:39:31
                    [username] => robe@gmail.com
                    [autor] => Roberto Mejia
                    [written] => 1
                    [picture] => d.jpg
                    [article_type_id] => 3
                    [article_type_name] => Eventos
                    [article_type_seo] => eventos
                    [category_id] => 2
                    [category_name] => Articulos
                    [category_seo] => articulos
                    [status] => 1
                    [status_name] => Active
                    [lang_id] => 1
                    [language] => es
                    [lang_namespace] => es_MX
                    [lang_status] => 1
                    [description] => Este es un articulo de eventos, el cual solamente contendria una descripcion, para cargar sus ADDONS correspondientes.
                )
*/
?>