<div class="announcement all-panel">

  <?php if( ! empty($this->announcement['items']) ):?>
    <?= empty($this->announcement['pagination_html']) ? '' : $this->announcement['pagination_html'] ?>
    <?php $core = App::module('Core')->getModel('Dates');?>
    <?php foreach( $this->announcement['items'] AS $announcement ): ?>
      <div class="block">
        <h2 class="no-line strong">
          <?=$announcement['title']?>
          <span><?=App::locale()->toDate($announcement['event_date'],'long')?></span>
        </h2>
        <a href="<?=App::base( App::xlat('route_announcement').$announcement['seo'] )?>">
          <img src="<?=App::media( $this->gallery_path . $core->toDate(8, $announcement['event_date']) .DS. $announcement['article_id'] .DS. $announcement['seo']. "_listing.jpg" ) ?>" width="295" height="170" alt="<?=$announcement['title']?>" title="<?=$announcement['title']?>" />
        </a>
      </div>
    <?php endforeach; ?>
    <?= empty($this->announcement['pagination_html']) ? '' : $this->announcement['pagination_html'] ?>

  <?php else:?>
    <h3 class="no-line empty-listing"> <?=App::xlat('LISTING_no_data_found')?> </h3>
  <?php endif;?>

</div>


<?php
/*
    [items] => Array
        (
            [0] => Array
                (
                    [id] => 143
                    [article_id] => 156
                    [title] => Articulo de prueba # 156
                    [seo] => probando-6
                    [created] => 2010-02-01 09:39:31
                    [publicated] => 2010-02-01 09:39:31
                    [username] => robe@gmail.com
                    [author] => Roberto Mejia
                    [written] => 1
                    [picture] => d.jpg
                    [article_type_id] => 3
                    [article_type_name] => Eventos
                    [article_type_seo] => eventos
                    [category_id] => 2
                    [category_name] => Articulos
                    [category_seo] => articulos
                    [status] => 1
                    [status_name] => Active
                    [lang_id] => 1
                    [language] => es
                    [lang_namespace] => es_MX
                    [lang_status] => 1
                    [description] => Este es un articulo de eventos, el cual solamente contendria una descripcion, para cargar sus ADDONS correspondientes.
                )
*/
?>