  <div class="announcement left-panel">
    <?= empty($this->articles['pagination_html']) ? '' : $this->articles['pagination_html'] ?>

    <?php $core = App::module('Core')->getModel('Dates');?>
    <?php foreach( $this->articles['items'] AS $article ): ?>
      <h1> <?=$article['title']?> </h1>
      <a href="<?=App::base( App::xlat('route_announcement').$article['seo'] )?>">
        <img src="<?=App::media( $this->gallery_path . $core->toDate(8, $article['publicated']) ."/". $article['article_id'] ."/". $article['seo']. "_listing.jpg" ) ?>" width="645" height="220" alt="<?=$article['title']?>" title="<?=$article['title']?>" />
      </a>
      <p class="bottom-line"><?=App::locale()->toDate($article['publicated'],'long')?></p>
      <p class="description"><?=$article['description']?></p>
    <?php endforeach; ?>

    <?= empty($this->articles['pagination_html']) ? '' : $this->articles['pagination_html'] ?>
  </div>

  <div class="right-panel">
    <h1>A ver que ponemos aqui<span>Sed congue, dui vel tristique mollis...</span></h1>
    <p><strong>Address Info</strong><br />123 Pine Street<br />Mycity, ST 19000</p>
    <p><strong>Email:</strong><a href="mailto:contact@mycompany.com"> contact@mycompany.com</a><br />
      <strong>Website:</strong> <a href="#">www.mycompany.com</a><br />
      <strong>Phone:</strong> 0800-123456 </p>
  </div>

<?php
/*
    [items] => Array
        (
            [0] => Array
                (
                    [id] => 143
                    [article_id] => 156
                    [title] => Articulo de prueba # 156
                    [seo] => probando-6
                    [created] => 2010-02-01 09:39:31
                    [publicated] => 2010-02-01 09:39:31
                    [username] => robe@gmail.com
                    [autor] => Roberto Mejia
                    [written] => 1
                    [picture] => d.jpg
                    [article_type_id] => 3
                    [article_type_name] => Eventos
                    [article_type_seo] => eventos
                    [category_id] => 2
                    [category_name] => Articulos
                    [category_seo] => articulos
                    [status] => 1
                    [status_name] => Active
                    [lang_id] => 1
                    [language] => es
                    [lang_namespace] => es_MX
                    [lang_status] => 1
                    [description] => Este es un articulo de eventos, el cual solamente contendria una descripcion, para cargar sus ADDONS correspondientes.
                )
*/
?>