  <div class="left-panel">
    <h2>
      <?=$this->media['title']?>
      <span><?=App::xlat('CONTENT_subtitle_multimedia')?></span>
    </h2>
    <?= eval('?>' . $this->media['article'] . '<?php ');?>
  </div>

  <div class="right-panel">
    <h2>A ver que ponemos aqui<span>Sed congue, dui vel tristique mollis...</span></h2>
    <p><strong>Address Info</strong><br />123 Pine Street<br />Mycity, ST 19000</p>
    <p><strong>Email:</strong><a href="mailto:contact@mycompany.com"> contact@mycompany.com</a><br />
      <strong>Website:</strong> <a href="#">www.mycompany.com</a><br />
      <strong>Phone:</strong> 0800-123456 </p>
  </div>
