
  <div class="bible left-panel">
    <h1>
      <?=str_replace("%cap%", $this->chapter, App::xlat('BIBLE_verses_topic') ) . $this->details['book']?>
      <span><?=App::xlat('CONTENT_subtitle_bible')?></span>
    </h1>
    <img height="150" width="645" title="<?=App::xlat('CONTENT_subtitle_bible')?>" alt="<?=App::xlat('CONTENT_subtitle_bible')?>" src="<?=App::media('/images/holy-bible-2.jpg') ?>" />
    <?php 
      $chapter_paginator = App::module('Addons')->renderBlock("bible/index","chaptersPaginator", array("seo" => $this->details['seo'], "chapters_total"=> $this->details['chapter'], "chapter" => $this->chapter ));
      $ds = "/"; 
    ?>
    <?=$chapter_paginator;?>

      <ol class="verse">
        <?php foreach($this->verses AS $verse): ?>
          <li>
            <a href="<?=App::base( App::xlat('route_bible') . $this->details['seo'] .$ds. $this->chapter .$ds. $verse['ver'] )?>">
              <?= $verse['texto'] ; ?>
            </a>
          </li>
        <?php endforeach; ?>
      </ol>

    <?=$chapter_paginator;?>

  </div>

  <div class="right-panel">
    <?=App::module('Addons')->renderBlock("bible/index","search")?>
    <?=App::module('Addons')->renderBlock("bible/index","books", array("book_id" => $this->details['book_id']))?>
    <?=App::module('Addons')->renderBlock("bible/index","bookDetail", array("details" => $this->details))?>
  </div>