
  <div class="bible left-panel">
    <h1>
      <?=str_replace("%cap%", $this->chapter, App::xlat('BIBLE_verses_topic') ) . $this->details['book']?>
      <span><?=App::xlat('CONTENT_subtitle_bible')?></span>
    </h1>

    <?php $chapter_paginator = App::module('Addons')->renderBlock("bible/index","chaptersPaginator", array("seo" => $this->details['seo'], "chapters_total"=> $this->details['chapter'], "chapter" => $this->chapter )); ?>
    <?=$chapter_paginator;?>

      <ol class="verse">
        <?php foreach($this->verses AS $verse): ?>
          <li> <?= $verse['texto'] ; ?> </li>
        <?php endforeach; ?>
      </ol>

    <?=$chapter_paginator;?>

  </div>

  <div class="right-panel">
    <?=App::module('Addons')->renderBlock("bible/index","bookDetail", array("details" => $this->details))?>
    <?=App::module('Addons')->renderBlock("bible/index","books", array("book_id" => $this->details['book_id']))?>
  </div>