  <div class="left-panel">
    <h1>
      <?=App::xlat('BIBLE_topic')?>
      <span><?=App::xlat('CONTENT_subtitle_bible')?></span>
    </h1>
    <img height="150" width="645" title="<?=App::xlat('CONTENT_subtitle_bible')?>" alt="<?=App::xlat('CONTENT_subtitle_bible')?>" src="<?=App::media('/images/holy-bible-2.jpg') ?>" />
    <table class="bible">
    <?php
      $settings = array( 'old' => array('add_col_on_iteration'=> 20 , 'move_to_column_one' => 39 ),
                         'new' => array('add_col_on_iteration'=> 53 , 'move_to_column_one' => 70 ));

      $testament = "";
      $iteration = 0;
      foreach($this->books AS $book){

        if( $testament != $book['testament'] ){
          $testament = $book['testament'];
          echo "<tr>  <th colspan='2' class='bible_books'>".  App::xlat('BIBLE_testament_' . $book['testament']) . "</th> </tr>";
          echo "<tr>  <td><ul>";
        }

        if( $iteration == $settings[$book['testament']]['add_col_on_iteration'] ){
          echo "</ul></td><td><ul>";
        }

        echo "<li> <a href='". App::base( App::xlat('route_bible') . $book['seo'] ) ."'>". $book['book'] . "</li>";
        $iteration++;

        if( $iteration == $settings[$book['testament']]['move_to_column_one'] ){
          echo "</ul></td></tr>";
        }

      }
    ?>
    </table>

  </div>

  <div class="right-panel">
    <?=App::module('Addons')->renderBlock("bible/index","search", array("form_type" => "advanced") )?>
  </div>

<?php
/*
$book
Array
(
    [book_id] => 1
    [book] => Génesis
    [seo] => genesis
    [testament] => 1
    [cap] => 50
)
*/
?>
