<?php
  $book_details = array('book'=>$this->book['book'], 'seo'=>$this->book['seo'], 'chapter'=>$this->book['chapter'], 'current_chapter'=>$this->verse['chapter'], 'current_verse'=>$this->verse['verse'], 'verses_in_chapter'=>$this->verse['verses_in_chapter'], 'verses'=>$this->book['verses'], 'testament'=>$this->book['testament'] );
?>

<div class="all-panel">
  <div id="bible-book">

    <div class="opened">

      <?=App::module('Addons')->renderBlock("bible/index","options", array("section" => "verse", "book_id" => $this->book['book_id'], "details" => $book_details) )?>

      <div class="top">
        <div class="t-left"></div> <div class="t-right"></div>
      </div>

      <div class="mid">
        <div class="current-book">
          <?php foreach($this->book['separated'] AS $key=>$char): ?>
            <?=$char."<br />"?>
          <?php endforeach; ?>
        </div>
        <div class="verse">
          <?=App::module('Addons')->renderBlock("bible/index", "versesPaginator", array("book"         => $this->book['seo'],
                                                                                        "chapter"      => $this->verse['chapter'],
                                                                                        "verse"        => $this->verse['verse'],
                                                                                        "verses_total" => $this->verse['verses_in_chapter'] ));?>
          <p><?=$this->verse['texto']; ?></p>
        </div>

      </div>

      <div class="bot">
        <div class="b-left"></div> <div class="b-right"></div>
      </div>
    </div>

  </div>
</div>

<?php
/*
$this->verse
Array
(
    [id] => 9
    [texto] => Y dijo Dios: Sea la luz;  y fue la luz.
    [verse] => 3
    [chapter] => 1
    [verses_in_chapter] => 31
)
$this->book
Array
(
    [book_id] => 1
    [book] => Génesis
    [seo] => genesis
    [lang_id] => 1
    [testament] => old
    [name] => Español
    [prefix] => es
    [namespace] => es_MX
    [status] => 1
    [verses] => 1533
    [chapter] => 50
    [separated] => Array
        (
            [0] => G
            [1] => e
            [2] => n
            [3] => e
            [4] => s
            [5] => i
            [6] => s
        )
)
*/
?>